[package]
name = "larsc/rojotesting"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@0.5.0"
Signal = "sleitnick/signal@1.4.1"
Promise = "evaera/promise@4.0.0"
Loader = "sleitnick/loader@2.0.0"
Net = "sleitnick/net@0.1.0"
TableUtil = "sleitnick/table-util@1.2.0"